name: .NET CI/CD

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - run: dotnet restore
    - run: dotnet build --configuration Release

  test:
    runs-on: windows-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - run: dotnet test

  deploy:
    runs-on: windows-latest
    needs: test
    steps:
    - run: echo "🎉 Deploy step executed (placeholder)"
